services:
  postgres-main:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-main-db-volume:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-main-db-volume:
